server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eatable?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user907
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



  security:
    user:
      name: user1
      password: 1234
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: YsJrZssQT5uMuONnqPfW
            client-secret: bAK4qOoccH
            redirect-uri: http://localhost:3000/login
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname
              - birthday
              - mobile
              - birthyear
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
app:
    upload_user:
      path: upload_user

    upload_partner:
      path: upload_partner

    upload_menu:
      path: upload_menu

    upload_store:
      path: upload_menu

    oauth2:
      password: 1234



jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  expiration: 86400000 # 86400000 # 1일
  refresh-token:
    expiration: 604800000  #7일
